// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyCoPilotReferencesExtension
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCopyFilePathsPackageString = "f5e53b6a-4f5f-4f87-b6d9-167b162f3b8b";
        public static Guid guidCopyFilePathsPackage = new Guid(guidCopyFilePathsPackageString);

        public const string guidCopyCoPilotReferencesPackageCmdSetString = "e903358c-f298-4653-a50b-c7853569396f";
        public static Guid guidCopyCoPilotReferencesPackageCmdSet = new Guid(guidCopyCoPilotReferencesPackageCmdSetString);

        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CopyCoPilotReferencesCommandId = 0x0100;
        public const int IDM_VS_CTXT_ITEMNODE = 0x0430;
    }
}
