// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyCoPilotReferencesExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "CopyCoPilotReferencesExtension.0b95f3f5-b282-4fdf-a015-6afee718201d";
        public const string Name = "Copy Copilot References";
        public const string Description = @"Copy selected file references for Copilot to the clipboard.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Eddie Green";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
